### ISSUE TITLE
Remote Endpoint error

### ISSUE THREAD

**Issue by dboone74** [bklavet/Echo-skill-to-control-Directv#24]
When trying to test from the dev site I keep getting the following error.

> The remote endpoint could not be called, or the response it returned was invalid.

I have confirmed my external IP and port forwarding is correct by going to http://xx.xx.xx.xx:8080/remote/processKey?key=pause&hold=keyPress from outside my network and it does work. 

I have double checked my App ID in the index file and the ARN #, and they are correct. I even tried reuploading the files a couple of times and I keep getting this error.

I checked the log files cloud watch and found the following

> 23:38:48 START RequestId: 9a7c16f4-d5fb-11e6-8d63-f141d0387b78 Version: $LATEST
> 23:38:48 Unable to import module 'index': Error at Function.Module._resolveFilename (module.js:325:15) at Function.Module._load (module.js:276:25) at Module.require (module.js:353:17) at require (internal/module.js:12:17)
> 23:38:48 END RequestId: 9a7c16f4-d5fb-11e6-8d63-f141d0387b78
> 23:38:48 REPORT RequestId: 9a7c16f4-d5fb-11e6-8d63-f141d0387b78	Duration: 23.56 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 15 MB

**Comment by dboone74** [comment]
I found the issue. I am on a Mac and I had to edit the index file name to include .txt to get my text editor to open it. I then deleted the extension, or so I thought, before I opened it. I open the "Get Info" window on the file and found that it had just hidden the extension rather than deleting it. Rezipped the files and uploaded them and now it is working.
